In [1]:
#importing modules
import numpy
import pandas as pd

# Week1

In [2]:
#1

#function creates an array, having all its positions as 'integer 1'
def create_numpy_ones_array(shape):
     return numpy.ones(shape,numpy.int8)

s=(3,8) #shape dimension
create_numpy_ones_array(s)


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [3]:
#2

#function creates an array, having all its positions as'integer 0'
def create_numpy_zeros_array(shape):
     return numpy.zeros(shape,numpy.int8)

s=(2,4) #shape dimension
create_numpy_zeros_array(s)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [4]:
#3

#function creates identity matrix of order x
def create_identity_numpy_array(x):
    a=numpy.zeros((x,x),numpy.int8)
    i=0
    while(i<x):
        j=0
        while(j<x):
            if(i==j):
                a[i][j]=numpy.ones((1,1),numpy.int8)
            j+=1
        i+=1
    return a

num=5 #order
create_identity_numpy_array(num)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [5]:
#4

#function that outputs cofactor matrix of the array 
def matrix_cofactor(arr):
    det = numpy.linalg.det(arr) #determinant
    if(det!=0):
        result = arr
        result = numpy.linalg.inv(arr).T * det
        return result
    else:
        return "The array is a singular matrix. Determinant cannot be found."
        

array=[[11,33],[55,77]]
matrix_cofactor(array)


array([[ 77., -55.],
       [-33.,  11.]])

In [6]:
#5

#function that outputs computed function(numpy array) or -1

def f1(X1,coef1,X2,coef2,seed1,seed2,seed3,shape1,shape2):
    s1=X1.shape
    s2=X2.shape
    
    if(shape1[0]!=s1[1] or shape2[0]!=s2[1]):
        return -1
    
    else:
        numpy.random.seed(seed1)
        w1=numpy.random.rand(shape1[0],shape1[1])
        numpy.random.seed(seed2)
        w2=numpy.random.rand(shape2[0],shape2[1])
        
        result= w1*(X1**coef1) + w2*(X2**coef2)
    return result

#values
X1=numpy.array([[11,22],[33,44]])
X2=numpy.array([[10,20],[30,40]])
shape1=(2,2)
shape2=(2,2)
coef1=2
coef2=6
seed1=0
seed2=1
seed3=4

f1(X1,coef1,X2,coef2,seed1,seed2,seed3,shape1,shape2)

array([[   417088.41113655,  46101113.73195145],
       [    84035.65116096, -60153239.57543848]])

In [7]:
#6

#function that outputs entire data, where the specific column(given as input), doesn't have NaN values.

def fill_with_mode(filename, input_column):
    df=pd.read_csv(filename)
    m=df[input_column].mode()[0]
    values={input_column:m}
    result=df.fillna(value=values)
    return result

file="example.csv"
col="Attribute A"
print("\n The following represents entire data, where column 'Attribute A' doesn't have NaN values.")
fill_with_mode(file, col)


 The following represents entire data, where column 'Attribute A' doesn't have NaN values.


SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         22.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         22.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11         22.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [8]:
#7

#function that outputs entire data, where the specific column(given as input), doesn't have NaN values.

def fill_with_group_average(df, group, input_column):    
    c=df[grp]
    result = df.groupby(group).transform(lambda x: x.fillna(x.mean()))
    result[grp]=c  
    return result

dataframe=pd.read_csv("example.csv")
grp="Attribute C"
col="Attribute A"
print("\n The following represents entire data, where column 'Attribute A' doesn't have NaN values.")
fill_with_group_average(dataframe, grp, col)


 The following represents entire data, where column 'Attribute A' doesn't have NaN values.


SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         51.5           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         43.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
9      10         81.0           45           B
10     11         24.5           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [9]:
#8

#function that outputs all rows, where 'Attribute B' column values are more than that column's average.

def get_rows_greater_than_avg(df,column):
    m=df.mean(axis=0, skipna = True, numeric_only= True)[column] 
    
    col=df[column]
    row=0
    for i in col:
        if(i>m):
            print(df[row:row+1],"\n")
        row+=1
    print("Average of '",column,"' column is:",m)
    return


dataframe=pd.read_csv("example.csv")
col="Attribute B"
print("\n The following represents all rows, where 'Attribute B' column values are more than that column's average:\n\n")
get_rows_greater_than_avg(dataframe, col)


 The following represents all rows, where 'Attribute B' column values are more than that column's average:


   SL.No  Attribute A  Attribute B Attribute C
0      1         12.0           44           A 

   SL.No  Attribute A  Attribute B Attribute C
5      6          NaN           45           C 

   SL.No  Attribute A  Attribute B Attribute C
7      8         22.0           78           B 

   SL.No  Attribute A  Attribute B Attribute C
9     10         81.0           45           B 

    SL.No  Attribute A  Attribute B Attribute C
11     12         56.0           35           C 

    SL.No  Attribute A  Attribute B Attribute C
12     13         33.0           67           A 

Average of ' Attribute B ' column is: 31.733333333333334


# Practice codes: numpy module

In [10]:
#1
numpy.ones((2,3),numpy.float64)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#2
numpy.zeros(4,numpy.int8)

array([0, 0, 0, 0], dtype=int8)

In [12]:
#3
numpy.random.rand(2,2)

array([[0.14675589, 0.09233859],
       [0.18626021, 0.34556073]])

In [13]:
#4
numpy.random.seed(2)

# Using numpy.random.seed(k) function below
numpy.random.rand(2,2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239]])

In [14]:
#4-continued
numpy.random.seed(2)

# Checking if numpy.random.seed(k) function below, gives same array as above
numpy.random.rand(2,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239]])

In [15]:
#5
list=[22,8,9]
numpy.array(list)

array([22,  8,  9])

In [16]:
#6
m=[[99,66,33],[30,60,90]]
a=numpy.array(m)
print(a[0][0])
a[0][0]=100
a

99


array([[100,  66,  33],
       [ 30,  60,  90]])

In [17]:
#7 
#element wise multiplication of 2 array

a1=numpy.array([[1,2],[3,4]])
a2=numpy.array([[5,6],[7,8]])
numpy.multiply(a1,a2)


array([[ 5, 12],
       [21, 32]])

In [18]:
#8
#matrix multiplication

a1=numpy.array([[1,2],[3,4]])
a2=numpy.array([[5,6],[7,8]])
numpy.matmul(a1,a2)


array([[19, 22],
       [43, 50]])

In [19]:
#9
x=numpy.array([1,2])
y=numpy.array([3,4])
numpy.dot(x,y)

11

In [20]:
#10
x=numpy.array([1,2])
y=numpy.array([4,5,6])
numpy.cross(x,y)

array([12, -6, -3])

In [21]:
#11
m=numpy.array([[1,2],[3,4]])
numpy.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
#12
m=numpy.array([[1,2],[3,4]])
numpy.transpose(m)

array([[1, 3],
       [2, 4]])

In [23]:
#13
m=numpy.array([[1,2],[3,4]])
numpy.linalg.det(m)

-2.0000000000000004

In [24]:
#14
m=numpy.array([[100,200],[300,400]])
m.shape

(2, 2)

# Practice codes: pandas module

In [25]:
#1
dataframe=pd.read_csv("example.csv") 
dataframe

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          NaN           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          NaN           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11          NaN           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [26]:
#2
a=[]
t=tuple(dataframe.columns)
for i in t:
    a.append(i)
a

#finding column names
# As "list(dataframe.columns)" was giving TypeError, the above code is used to convert "object" datatype to "list" datatype.

['SL.No', 'Attribute A', 'Attribute B', 'Attribute C']

In [27]:
#3
a=[]
t=tuple(dataframe['SL.No'])
for i in t:
    a.append(i)
a



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [28]:
#4
print(dataframe.iloc[0]) #first row
dataframe.iloc[1] #second row


SL.No             1
Attribute A    12.0
Attribute B      44
Attribute C       A
Name: 0, dtype: object


SL.No            2
Attribute A    NaN
Attribute B     22
Attribute C      B
Name: 1, dtype: object

In [29]:
#5
print(dataframe.iloc[:,0]) #first column
dataframe.iloc[:,1] #second column

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
Name: SL.No, dtype: int64


0     12.0
1      NaN
2     31.0
3     19.0
4     22.0
5      NaN
6     41.0
7     22.0
8     90.0
9     81.0
10     NaN
11    56.0
12    33.0
13    21.0
14    78.0
Name: Attribute A, dtype: float64

In [30]:
#6
dataframe[0:2]

SL.No  Attribute A  Attribute B Attribute C
0      1         12.0           44           A
1      2          NaN           22           B

In [31]:
#7
dataframe.mean(axis=0, skipna = True, numeric_only= True) 

SL.No           8.000000
Attribute A    42.166667
Attribute B    31.733333
dtype: float64

In [32]:
#8
x=dataframe.groupby("Attribute C")
for key,value in x:
    print(key,value)

A     SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
2       3         31.0           13           A
4       5         22.0           24           A
10     11          NaN           22           A
12     13         33.0           67           A
B    SL.No  Attribute A  Attribute B Attribute C
1      2          NaN           22           B
7      8         22.0           78           B
9     10         81.0           45           B
C     SL.No  Attribute A  Attribute B Attribute C
3       4         19.0           13           C
5       6          NaN           45           C
6       7         41.0           21           C
11     12         56.0           35           C
13     14         21.0           12           C
14     15         78.0           14           C


In [33]:
#9
dataframe

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          NaN           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          NaN           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11          NaN           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [34]:
#9-continued
#(i)
dataframe.fillna(0)

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          0.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          0.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21           0
9      10         81.0           45           B
10     11          0.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [35]:
#9-continued
#(ii)
dataframe.fillna(method='ffill')

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         12.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         22.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21           B
9      10         81.0           45           B
10     11         81.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [36]:
#9-continued
#(iii)
dataframe.fillna(method='bfill')

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         31.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         41.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21           B
9      10         81.0           45           B
10     11         56.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [37]:
#9-continued
#(iv)
values={"Attribute A":0,"Attribute C":'c'}
dataframe.fillna(value=values)

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          0.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          0.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21           c
9      10         81.0           45           B
10     11          0.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [38]:
#END